modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/StructuredCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structured-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="structuredcrafting"
version="${file.jarVersion}"
displayName="StructuredCrafting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/structured-crafting.json"
description='''
Craft stuff in your world, automatically.
'''
[[dependencies.structuredcrafting]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.20.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structuredcrafting]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structuredcrafting]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
